[package]
name = "axum-web-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.15"
hyper = "0.14.20"
serde = "1.0.144"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread", "signal"] }
tonic = "0.8.1"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
utoipa = "2.0.1"
utoipa-swagger-ui = { version = "2.0.1", features = ["axum"] }

prost = "0.11"

[build-dependencies]
tonic-build = "0.8"
