[package]
name = "axum-demo"
version = "0.1.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Web
axum = { version = "0.6.1", features = ["headers", "macros"] }
axum-extra = { version = "0.4.2", features = ["typed-routing"] }
tower = { version = "0.4.13", features = ["retry"] }
tower-http = { version = "0.3.4", features = [
    "tracing",
    "trace",
    "request-id",
    "propagate-header",
    "sensitive-headers",
    "set-header",
    "compression-gzip",
] }
http = "0.2.8"
hyper = "0.14.23"
tokio = { version = "1.23.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

# Docs
utoipa = { version = "2.4.2", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "3.0.1", features = ["axum"] }

# gRPC
tonic = "0.8.3"
prost = "0.11.3"

# Integration
sqlx = { version = "0.6.2", default_features = false, features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    "offline",
] }
reqwest = { version = "0.11.12", features = ["json"] }
lapin = "2.1.1"

# Serialization
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.87"

# Tracing
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "json"] }
tracing-appender = "0.2.2"
tracing-opentelemetry = "0.18.0"
opentelemetry-jaeger = "0.17.0"
opentelemetry = { version = "0.18.0", default-features = false, features = [
    "trace",
] }

# Utilities
config = "0.13.2"
uuid = { version = "1.2.0", features = ["v4"] }
bcrypt = "0.13.0"
thiserror = "1.0.37"
anyhow = "1.0.65"
chrono = { version = "0.4.22", features = ["serde"] }
cached = "0.41.0"
bytes = "1.3.0"
futures = "0.3.25"

[build-dependencies]
tonic-build = "0.8.4"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "criterion"
harness = false
