[package]
name = "axum-demo"
version = "0.1.22"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]

# Web
axum = { version = "0.6.1", features = ["headers", "macros"] }
axum-extra = { version = "0.4.2", features = [
    "typed-routing",
    "json-lines",
    "spa",
] }
tower = { version = "0.4.13", features = ["retry"] }
tower-http = { version = "0.3.4", features = [
    "tracing",
    "trace",
    "request-id",
    "propagate-header",
    "sensitive-headers",
    "set-header",
    "compression-gzip",
    "limit",
    "catch-panic",
] }
http = "0.2.8"
hyper = "0.14.23"
tokio = { version = "1.24.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

# Docs
utoipa = { version = "3.0.0", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "3.0.2", features = ["axum"] }

# gRPC
tonic = "0.8.3"
prost = "0.11.3"

# GraphQL
async-graphql = "5.0.5"
async-graphql-axum = "5.0.5"

# Integration
sqlx = { version = "0.6.2", default_features = false, features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    "offline",
] }
reqwest = { version = "0.11.12", default-features = false, features = ["json"] }
lapin = { version = "2.1.1", default-features = false }
deadpool-lapin = "0.10.0"
lettre = "0.10.1"

# Serialization
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.87"

# Tracing
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", default-features = false, features = [
    "env-filter",
    "json",
    "ansi",
] }
tracing-appender = "0.2.2"
tracing-opentelemetry = { version = "0.18.0", default-features = false }
tracing-error = "0.2.0"
opentelemetry-jaeger = "0.17.0"
opentelemetry = { version = "0.18.0", default-features = false, features = [
    "trace",
] }

# Utilities
config = "0.13.2"
uuid = { version = "1.2.0", features = ["v4"] }
bcrypt = "0.13.0"
thiserror = "1.0.37"
color-eyre = "0.6.2"
chrono = { version = "0.4.23", default-features = false, features = ["serde"] }
cached = "0.42.0"
bytes = "1.3.0"
futures = "0.3.25"
async-stream = "0.3.3"
slab = "0.4.7"
dotenv = "0.15.0"
tokio-cron-scheduler = "0.9.3"

[build-dependencies]
tonic-build = "0.8.4"

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }

[[bench]]
name = "criterion"
harness = false
