[server]
http_address = "0.0.0.0"
http_port = 8080
grpc_address = "0.0.0.0"
grpc_port = 3009
session_duration = "1min"

[database]
host = "localhost"
port = 5432
username = "postgres"
password = "password"
database_name = "axum-demo"

[logging]
rust_log = "warn,tower_http=trace,axum_demo=debug"
jaeger_host = "http://localhost"
jaeger_port = 4317

[mq]
host = "localhost"
port = 5672
username = "guest"
password = "guest"

[email]
username = "changeme"
password = "changeme"
host = "localhost"
