FROM ubuntu:latest

# Copy prebuilt resources
COPY target/release/axum-demo /usr/local/bin/axum-demo
COPY config.toml config.toml

EXPOSE 80
ENV RUST_LOG warn,axum_demo=debug
ENV APP__SERVER__HTTP_PORT 80
ENTRYPOINT ["/usr/local/bin/axum-demo"]
