FROM debian:buster-slim

# Copy prebuilt resources
COPY target/release/axum-demo .
COPY target/doc/axum_demo doc
COPY config.toml .

# Set environment variables
ENV RUST_LOG info,axum_web_demo=debug,sqlx=off

ENTRYPOINT ["./axum-demo"]
