services:

  axum-demo:
    profiles:
      - app
    build: .
    ports:
      - 3000
    environment:
      - APP__SERVER__HTTP_PORT=3000
      - APP__DATABASE__HOST=postgres
      - APP__JAEGER__HOST=jaeger
      - APP__MQ__HOST=rabbitmq
    depends_on:
      - postgres
      - jaeger
      - rabbitmq

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  jaeger:
    image: jaegertracing/all-in-one:1.37
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
      - 4317:4317
      - 4318:4318
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  rabbitmq:
    image: rabbitmq:3.11.5-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 15692:15692
      - 5672:5672

  nginx:
    profiles:
      - app
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    healthcheck:
      test: curl -f http://nginx:8080/api/hello || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 1s
    depends_on:
      - axum-demo
