name: Build and Deploy

on:
  push:
    branches: [ "**" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.6.2
  REGISTRY: "registry.digitalocean.com/rudsvar"
  IMAGE_NAME: "axum-demo"
  DATABASE_URL: ${{ secrets.DATABASE_URL }} # For sqlx

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:3.11.5
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v3

      - name: Install protoc for gRPC
        run: sudo apt-get install -y protobuf-compiler

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check fmt
        run: cargo fmt --check

      - name: Install sqlx-cli
        run: |
          cargo install sqlx-cli \
            --version=${{ env.SQLX_VERSION }} \
            --features=postgres,rustls \
            --no-default-features \
            --locked

      - name: Set up database
        run: sqlx database setup

      - name: Check sqlx-data.json
        run: cargo sqlx prepare --check -- --lib

      - name: Run cargo test
        run: cargo test

  deploy:
    if: github.ref == 'refs/heads/main' && false
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build . -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
