name: Build and Test

on:
  push:
    branches: [ "**" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.7.2
  DATABASE_URL: ${{ secrets.DATABASE_URL }} # For sqlx

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:3.11.5
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v4

      - name: Install protoc for gRPC
        run: sudo apt-get install -y protobuf-compiler

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check fmt
        run: cargo fmt --check

      - name: Install sqlx-cli
        run: |
          cargo install sqlx-cli \
            --version=${{ env.SQLX_VERSION }} \
            --features=postgres,rustls \
            --no-default-features \
            --locked

      - name: Set up database
        run: sqlx database setup

      - name: Check sqlx-data.json
        run: cargo sqlx prepare --check -- --lib

      - name: Run cargo test
        run: cargo test
