name: Build

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.6.2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:3.11.5
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v3

      - name: Install protoc for gRPC
        run: sudo apt-get install -y protobuf-compiler

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Cache sqlx-cli
        uses: actions/cache@v3
        id: cache-sqlx
        with:
          path: |
            ~/.cargo/bin/sqlx
          key: ${{ runner.os }}-sqlx-${{ env.SQLX_VERSION }}

      - name: Install sqlx-cli
        uses: actions-rs/cargo@v1
        if: steps.cache-sqlx.outputs.cache-hit == false
        with:
          command: install
          args: >
            sqlx-cli
            --force
            --version=${{ env.SQLX_VERSION }}
            --features=postgres,rustls
            --no-default-features
            --locked

      - name: Check fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Set up database
        run: sqlx database setup

      - name: Check sqlx-data.json
        run: cargo sqlx prepare --check -- --lib

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
