name: CI

on:
  push:
    branches:
      - main
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    env:
      SQLX_VERSION: 0.6.2
      CARGO_BUMP_VERSION: 1.1.0
    steps:
      - uses: actions/checkout@v3

      - name: Install protoc for gRPC
        run: sudo apt-get install -y protobuf-compiler

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v3

      - name: Cache sqlx-cli
        uses: actions/cache@v3
        id: cache-sqlx
        with:
          path: |
            ~/.cargo/bin/sqlx
          key: ${{ runner.os }}-sqlx-${{ env.SQLX_VERSION }}-${{ env.SQLX_FEATURES }}

      - name: Install sqlx-cli
        uses: actions-rs/cargo@v1
        if: steps.cache-sqlx.outputs.cache-hit == false
        with:
          command: install
          args: >
            sqlx-cli
            --force
            --version=${{ env.SQLX_VERSION }}
            --features=postgres,rustls
            --no-default-features
            --locked

      - name: Cache cargo-bump
        uses: actions/cache@v3
        id: cache-cargo-bump
        with:
          path: |
            ~/.cargo/bin/cargo-bump
          key: ${{ runner.os }}-cargo-bump-${{ env.CARGO_BUMP_VERSION }}-${{ env.CARGO_BUMP_VERSION }}

      - name: Install cargo-bump
        uses: actions-rs/cargo@v1
        if: steps.cache-cargo-bump.outputs.cache-hit == false
        with:
          command: install
          args: >
            cargo-bump
            --force
            --version=${{ env.CARGO_BUMP_VERSION }}
            --locked

      - name: Set up database
        run: sqlx database setup

      - name: Verify that sqlx-data.json is up to date
        run: cargo sqlx prepare --check -- --lib

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run cargo fmt

      - name: Run cargo bump
        uses: actions-rs/cargo@v1
        with:
          command: bump

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v3

      - name: Run cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
