name: Deploy

on:
  # Release
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: write # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo bump
        run: cargo install cargo-bump

      - name: Bump version to release version
        run: |
          cargo bump "$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')"
          cargo generate-lockfile

      - name: Commit version bump
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml Cargo.lock
          git commit -m "Bump version to ${{ github.event.release.tag_name }}"

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: rudsvar.azurecr.io
          registryUsername: ${{ secrets.MYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYAPP_REGISTRY_PASSWORD }}
          containerAppName: my-app
          resourceGroup: rudsvar_rg
          imageToBuild: rudsvar.azurecr.io/my-app:${{ github.sha }}

      - name: Push version bump
        run: git push origin HEAD:${{ github.ref }}
